<?php

define('_KIG_COMMENT_INSTALL', 'Installation of module ');
define('_KIG_MODE_EMPLOI', 'help in docs/install.txt');
define('_KIG_KIG_MSG', 'This file install.php was generated by');
define('_KIG_TABLES_CREEES', 'Tables created !!!');
define('_KIG_INSERT_TABLE', 'Insert in table ');
define('_KIG_INSERT_TABLES', 'Insert some values in the tables');
define('_KIG_INSERT_OK', 'Inserts done !');
define('_KIG_CREATE_TABLE', 'CREATE TABLE ');
define('_KIG_INSTALL_OK', ' Install complete ');
define('_KIG_DELREP', 'You can(must) delete the directory : ');
//define("_KIG_","");
